# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: http_record.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='http_record.proto',
  package='MahimahiProtobufs',
  syntax='proto2',
  serialized_pb=_b('\n\x11http_record.proto\x12\x11MahimahiProtobufs\"^\n\x0bHTTPMessage\x12\x12\n\nfirst_line\x18\x01 \x01(\x0c\x12-\n\x06header\x18\x02 \x03(\x0b\x32\x1d.MahimahiProtobufs.HTTPHeader\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\"(\n\nHTTPHeader\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\"\xe8\x01\n\x0fRequestResponse\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x39\n\x06scheme\x18\x03 \x01(\x0e\x32).MahimahiProtobufs.RequestResponse.Scheme\x12/\n\x07request\x18\x04 \x01(\x0b\x32\x1e.MahimahiProtobufs.HTTPMessage\x12\x30\n\x08response\x18\x05 \x01(\x0b\x32\x1e.MahimahiProtobufs.HTTPMessage\"\x1d\n\x06Scheme\x12\x08\n\x04HTTP\x10\x01\x12\t\n\x05HTTPS\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REQUESTRESPONSE_SCHEME = _descriptor.EnumDescriptor(
  name='Scheme',
  full_name='MahimahiProtobufs.RequestResponse.Scheme',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HTTP', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HTTPS', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=382,
  serialized_end=411,
)
_sym_db.RegisterEnumDescriptor(_REQUESTRESPONSE_SCHEME)


_HTTPMESSAGE = _descriptor.Descriptor(
  name='HTTPMessage',
  full_name='MahimahiProtobufs.HTTPMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_line', full_name='MahimahiProtobufs.HTTPMessage.first_line', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='header', full_name='MahimahiProtobufs.HTTPMessage.header', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='MahimahiProtobufs.HTTPMessage.body', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=134,
)


_HTTPHEADER = _descriptor.Descriptor(
  name='HTTPHeader',
  full_name='MahimahiProtobufs.HTTPHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='MahimahiProtobufs.HTTPHeader.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='MahimahiProtobufs.HTTPHeader.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=176,
)


_REQUESTRESPONSE = _descriptor.Descriptor(
  name='RequestResponse',
  full_name='MahimahiProtobufs.RequestResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='MahimahiProtobufs.RequestResponse.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='MahimahiProtobufs.RequestResponse.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scheme', full_name='MahimahiProtobufs.RequestResponse.scheme', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request', full_name='MahimahiProtobufs.RequestResponse.request', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response', full_name='MahimahiProtobufs.RequestResponse.response', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUESTRESPONSE_SCHEME,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=411,
)

_HTTPMESSAGE.fields_by_name['header'].message_type = _HTTPHEADER
_REQUESTRESPONSE.fields_by_name['scheme'].enum_type = _REQUESTRESPONSE_SCHEME
_REQUESTRESPONSE.fields_by_name['request'].message_type = _HTTPMESSAGE
_REQUESTRESPONSE.fields_by_name['response'].message_type = _HTTPMESSAGE
_REQUESTRESPONSE_SCHEME.containing_type = _REQUESTRESPONSE
DESCRIPTOR.message_types_by_name['HTTPMessage'] = _HTTPMESSAGE
DESCRIPTOR.message_types_by_name['HTTPHeader'] = _HTTPHEADER
DESCRIPTOR.message_types_by_name['RequestResponse'] = _REQUESTRESPONSE

HTTPMessage = _reflection.GeneratedProtocolMessageType('HTTPMessage', (_message.Message,), dict(
  DESCRIPTOR = _HTTPMESSAGE,
  __module__ = 'http_record_pb2'
  # @@protoc_insertion_point(class_scope:MahimahiProtobufs.HTTPMessage)
  ))
_sym_db.RegisterMessage(HTTPMessage)

HTTPHeader = _reflection.GeneratedProtocolMessageType('HTTPHeader', (_message.Message,), dict(
  DESCRIPTOR = _HTTPHEADER,
  __module__ = 'http_record_pb2'
  # @@protoc_insertion_point(class_scope:MahimahiProtobufs.HTTPHeader)
  ))
_sym_db.RegisterMessage(HTTPHeader)

RequestResponse = _reflection.GeneratedProtocolMessageType('RequestResponse', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTRESPONSE,
  __module__ = 'http_record_pb2'
  # @@protoc_insertion_point(class_scope:MahimahiProtobufs.RequestResponse)
  ))
_sym_db.RegisterMessage(RequestResponse)


# @@protoc_insertion_point(module_scope)
