https://www.thestar.com
https://www.thestar.com/business/real_estate.html
https://www.thestaradvisers.com/Portal/default.aspx
https://www.thestar.com/news/gta/2021/03/05/where-can-i-get-my-covid-19-vaccine-use-our-table-to-look-up-your-public-health-units-plan.html
https://www.thestar.com/news/gta/2021/03/05/where-can-i-get-my-covid-19-vaccine-use-our-table-to-look-up-your-public-health-units-plan.html
https://www.thestar.com/sports/bluejays.html
https://apps.apple.com/ca/app/thestar-com-iphone/id379481068
https://www.thestar.com/long-term-care.html 
https://www.thestar.com/sports/leafs.html
https://www.thestar.com/news/gta/2021/03/09/how-fast-is-fast-enough-star-tracker-reveals-the-mega-gap-between-ontarios-covid-19-vaccination-goals-and-reality.html
https://www.thestar.com/long-term-care.html 
https://play.google.com/store/apps/details?id=com.thestar.www
https://www.thestar.com/sports/leafs.html
https://www.thestar.com/life/fashion_style.html
https://www.thestar.com/sports/bluejays.html
